CREATE DATABASE animal;

USE animal;

CREATE TABLE cadastro (
id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
dono VARCHAR(100) NOT NULL,
especie VARCHAR(100) NOT NULL,
raca VARCHAR(100) NOT NULL,
nascimento DATE NOT NULL
);